// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package qa_test

import (
	"context"
	"github.com/kyuff/qa"
	"sync"
)

// Ensure, that StubMock does implement qa.Stub.
// If this is not the case, regenerate this file with moq.
var _ qa.Stub = &StubMock{}

// StubMock is a mock implementation of qa.Stub.
//
//	func TestSomethingThatUsesStub(t *testing.T) {
//
//		// make and configure a mocked qa.Stub
//		mockedStub := &StubMock{
//			StartFunc: func(ctx context.Context) error {
//				panic("mock out the Start method")
//			},
//			StopFunc: func(ctx context.Context)  {
//				panic("mock out the Stop method")
//			},
//			WaitFunc: func(ctx context.Context)  {
//				panic("mock out the Wait method")
//			},
//		}
//
//		// use mockedStub in code that requires qa.Stub
//		// and then make assertions.
//
//	}
type StubMock struct {
	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context) error

	// StopFunc mocks the Stop method.
	StopFunc func(ctx context.Context)

	// WaitFunc mocks the Wait method.
	WaitFunc func(ctx context.Context)

	// calls tracks calls to the methods.
	calls struct {
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Wait holds details about calls to the Wait method.
		Wait []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockStart sync.RWMutex
	lockStop  sync.RWMutex
	lockWait  sync.RWMutex
}

// Start calls StartFunc.
func (mock *StubMock) Start(ctx context.Context) error {
	if mock.StartFunc == nil {
		panic("StubMock.StartFunc: method is nil but Stub.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedStub.StartCalls())
func (mock *StubMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *StubMock) Stop(ctx context.Context) {
	if mock.StopFunc == nil {
		panic("StubMock.StopFunc: method is nil but Stub.Stop was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc(ctx)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedStub.StopCalls())
func (mock *StubMock) StopCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}

// Wait calls WaitFunc.
func (mock *StubMock) Wait(ctx context.Context) {
	if mock.WaitFunc == nil {
		panic("StubMock.WaitFunc: method is nil but Stub.Wait was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockWait.Lock()
	mock.calls.Wait = append(mock.calls.Wait, callInfo)
	mock.lockWait.Unlock()
	mock.WaitFunc(ctx)
}

// WaitCalls gets all the calls that were made to Wait.
// Check the length with:
//
//	len(mockedStub.WaitCalls())
func (mock *StubMock) WaitCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockWait.RLock()
	calls = mock.calls.Wait
	mock.lockWait.RUnlock()
	return calls
}
