// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package qa_test

import (
	"context"
	"github.com/kyuff/qa"
	"net/http"
	"sync"
)

// Ensure, that StubMock does implement qa.Stub.
// If this is not the case, regenerate this file with moq.
var _ qa.Stub = &StubMock{}

// StubMock is a mock implementation of qa.Stub.
//
//	func TestSomethingThatUsesStub(t *testing.T) {
//
//		// make and configure a mocked qa.Stub
//		mockedStub := &StubMock{
//			HandlerFunc: func() http.Handler {
//				panic("mock out the Handler method")
//			},
//			ProbeFunc: func() error {
//				panic("mock out the Probe method")
//			},
//			StartFunc: func(ctx context.Context) error {
//				panic("mock out the Start method")
//			},
//			StopFunc: func(ctx context.Context)  {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedStub in code that requires qa.Stub
//		// and then make assertions.
//
//	}
type StubMock struct {
	// HandlerFunc mocks the Handler method.
	HandlerFunc func() http.Handler

	// ProbeFunc mocks the Probe method.
	ProbeFunc func() error

	// StartFunc mocks the Start method.
	StartFunc func(ctx context.Context) error

	// StopFunc mocks the Stop method.
	StopFunc func(ctx context.Context)

	// calls tracks calls to the methods.
	calls struct {
		// Handler holds details about calls to the Handler method.
		Handler []struct {
		}
		// Probe holds details about calls to the Probe method.
		Probe []struct {
		}
		// Start holds details about calls to the Start method.
		Start []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockHandler sync.RWMutex
	lockProbe   sync.RWMutex
	lockStart   sync.RWMutex
	lockStop    sync.RWMutex
}

// Handler calls HandlerFunc.
func (mock *StubMock) Handler() http.Handler {
	if mock.HandlerFunc == nil {
		panic("StubMock.HandlerFunc: method is nil but Stub.Handler was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHandler.Lock()
	mock.calls.Handler = append(mock.calls.Handler, callInfo)
	mock.lockHandler.Unlock()
	return mock.HandlerFunc()
}

// HandlerCalls gets all the calls that were made to Handler.
// Check the length with:
//
//	len(mockedStub.HandlerCalls())
func (mock *StubMock) HandlerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHandler.RLock()
	calls = mock.calls.Handler
	mock.lockHandler.RUnlock()
	return calls
}

// Probe calls ProbeFunc.
func (mock *StubMock) Probe() error {
	if mock.ProbeFunc == nil {
		panic("StubMock.ProbeFunc: method is nil but Stub.Probe was just called")
	}
	callInfo := struct {
	}{}
	mock.lockProbe.Lock()
	mock.calls.Probe = append(mock.calls.Probe, callInfo)
	mock.lockProbe.Unlock()
	return mock.ProbeFunc()
}

// ProbeCalls gets all the calls that were made to Probe.
// Check the length with:
//
//	len(mockedStub.ProbeCalls())
func (mock *StubMock) ProbeCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockProbe.RLock()
	calls = mock.calls.Probe
	mock.lockProbe.RUnlock()
	return calls
}

// Start calls StartFunc.
func (mock *StubMock) Start(ctx context.Context) error {
	if mock.StartFunc == nil {
		panic("StubMock.StartFunc: method is nil but Stub.Start was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStart.Lock()
	mock.calls.Start = append(mock.calls.Start, callInfo)
	mock.lockStart.Unlock()
	return mock.StartFunc(ctx)
}

// StartCalls gets all the calls that were made to Start.
// Check the length with:
//
//	len(mockedStub.StartCalls())
func (mock *StubMock) StartCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStart.RLock()
	calls = mock.calls.Start
	mock.lockStart.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *StubMock) Stop(ctx context.Context) {
	if mock.StopFunc == nil {
		panic("StubMock.StopFunc: method is nil but Stub.Stop was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc(ctx)
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedStub.StopCalls())
func (mock *StubMock) StopCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
